---
- name: Gather required facts
  import_tasks: facts.yaml

- name: Ensure all farmers are mounted
  import_tasks: storage.yaml
  when: attached_farm_uuids and attached_farm_uuids | length > 0

- name: Setup Chia miner
  import_tasks: miner.yaml
  when: attached_farm_uuids and attached_farm_uuids | length > 0
