---
- name: Ensure dependencies
  become: yes
  package:
    name:
    - unzip
    - screen
  when: not farmer_is_running

- name: Ensure temporary directory exists
  file:
    path: /tmp/hpool-miner
    state: directory
  when: not farmer_is_running

- name: Fetch hpool miner binary
  unarchive:
    src: "https://github.com/hpool-dev/chia-miner/releases/download/{{ hpool_miner_version }}/HPool-Miner-chia-{{ hpool_miner_version }}-linux.zip"
    dest: /tmp/hpool-miner
    remote_src: yes
  when: not farmer_is_running

- name: Ensure installation directory exists
  file:
    path: "{{ hpool_miner_install_path }}"
    state: directory
  when: not farmer_is_running

- name: Copy hpool miner binary to installation path
  copy:
    src: /tmp/hpool-miner/linux/hpool-miner-chia
    dest: "{{ hpool_miner_install_path }}/hpool-miner"
    mode: a+x
  when: not farmer_is_running

- name: Create hpool config
  template:
    src: templates/config.yaml.j2
    dest: "{{ hpool_miner_install_path }}/config.yaml"
  when: attached_farm_uuids is defined

- name: Create farmer service
  become: yes
  template:
    src: templates/chia-farmer.service.j2
    dest: /etc/systemd/system/chia-farmer.service
  when: not farmer_is_running and attached_farm_uuids is defined

- name: Configure farmer service
  become: yes
  systemd:
    name: chia-farmer
    enabled: yes
    state: started
  when: not farmer_is_running and attached_farm_uuids is defined

- name: Restart previous farmer service
  become: yes
  systemd:
    name: chia-farmer
    state: restarted
  when: farmer_is_running and attached_farm_uuids is defined

- name: Stop farmer service if there is no attached farm
  become: yes
  systemd:
    name: chia-farmer
    enabled: no
    state: stopped
  when: not attached_farm_uuids is defined
