---
- name: Check AUR dependencies
  ignore_errors: yes
  shell: "pacman -Qs {{ item }}"
  with_items: &aur_packages
  - insync
  register: installed_aur_packages

- name: Install AUR dependencies
  command: "yay -S --noconfirm {{ item }}"
  with_items: *aur_packages
  when: installed_aur_packages.failed is defined and installed_aur_packages.failed == true

- name: Link Google Drive folders to Home
  file:
    src: "{{ home_dir_path }}/Drive/{{ item }}"
    dest: "{{ home_dir_path }}/{{ item }}"
    force: yes
    state: link
  with_items:
  - Videos
  - Temporary
  - Pictures
  - Downloads
  - Documents
  - Desktop
  - Archive


