---
- name: Check AUR dependencies
  ignore_errors: yes
  shell: "pacman -Qs {{ item }}"
  with_items: &aur_packages
  - insync
  register: installed_aur_packages

- name: Install AUR dependencies
  command: "yay -S --noconfirm {{ item }}"
  with_items: *aur_packages
  when: installed_aur_packages.failed is defined and installed_aur_packages.failed == true

- name: Mount Google Drive folders to Home
  become: yes
  template:
    src: templates/drive-folder.mount.j2
    dest: /etc/systemd/system/home-{{ ansible_user }}-{{ item }}.mount
  with_items: &mounted_drive_folders
  - Videos
  - Temporary
  - Pictures
  - Downloads
  - Documents
  - Desktop
  - Archive

- name: Enable systemd Google Drive folders services
  become: yes
  systemd:
    name: home-{{ ansible_user }}-{{ item }}.mount
    enabled: yes
    state: started
  with_items: *mounted_drive_folders

- name: Ensure Google Drive folders are owner by host user
  become: yes
  file:
    path: "{{ home_dir_path }}/Drive"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: Ensure Google Drive mounted folders are owner by host user
  become: yes
  file:
    path: "{{ home_dir_path }}/Drive/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items: *mounted_drive_folders
