---
- name: Ensure local fonts directory exists
  file:
    path: "{{ local_dir_path }}/share/fonts"
    state: directory

# SF Mono
# -------------------------------------------------------------------------------------------------
- name: Checking SF Mono installation
  stat:
    path: "{{ local_dir_path }}/share/fonts/SF-Mono-Nerd-Font"
  register: sf_mono_installation

- name: Fetch SF Mono font
  unarchive:
    src: https://github.com/epk/SF-Mono-Nerd-Font/releases/download/v15.0d5e1/SF-Mono-Nerd-Font.zip
    dest: "{{ local_dir_path }}/share/fonts"
    remote_src: yes
  when: sf_mono_installation.stat.exists == false

# SF Pro Display
# -------------------------------------------------------------------------------------------------
- name: Checking SF Pro Display installation
  stat:
    path: "{{ local_dir_path }}/share/fonts/San-Francisco-Pro-Fonts-master"
  register: sf_pro_installation

- name: Fetch SF Pro Display font
  unarchive:
    src: https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts/archive/refs/heads/master.zip
    dest: "{{ local_dir_path }}/share/fonts"
    remote_src: yes
  when: sf_pro_installation.stat.exists == false

# Hasklig
# -------------------------------------------------------------------------------------------------
- name: Checking Hasklig installation
  stat:
    path: "{{ local_dir_path }}/share/fonts/OTF"
  register: hasklig_installation

- name: Fetch Hasklig font
  unarchive:
    src: https://github.com/i-tu/Hasklig/releases/download/v1.2/Hasklig-1.2.zip
    dest: "{{ local_dir_path }}/share/fonts"
    remote_src: yes
  when: hasklig_installation.stat.exists == false
