---
- name: Register variable regarding Chia Blockchain installation path
  stat:
    path: "{{ chia_install_path }}"
  register: chia_installation

- name: Ensure local src directory
  file:
    path: "{{ install_src_path }}"
    state: directory
  when: chia_installation.stat.exists == false

- name: Fetch Chia Blockchain source code
  git:
    repo: https://github.com/Chia-Network/chia-blockchain.git
    dest: "{{ chia_install_path }}"
  when: chia_installation.stat.exists == false

- name: Ensure install script is executable
  file:
    dest: "{{ chia_install_path }}/install.sh"
    mode: a+x

- name: Install Chia Blockchain
  shell: "./install.sh"
  args:
    chdir: "{{ chia_install_path }}"

- name: Init Chia mainnet
  command: "{{ chia_bin }} init"

- name: Copy Chia keypair temporary file
  copy:
    src: files/chia-mnemonics.txt
    dest: /tmp/chia-mnemonics.txt
    decrypt: yes

- name: Add Chia keypair
  command: "{{ chia_bin }} keys add -f /tmp/chia-mnemonics.txt"

- name: Remove Chia keypair temporary file
  file:
    path: /tmp/chia-mnemonics.txt
    state: absent

- name: Create node service
  become: yes
  template:
    src: templates/chia-node.service.j2
    dest: /etc/systemd/system/chia-node.service
