---
- name: Checking if Chia Node is running
  service_facts:

- name: Setup Chia Blockchain
  import_tasks: chia-blockchain.yaml
  when: ansible_facts.services['chia-node.service'].state != 'running'

- name: Setup Chia miner
  import_tasks: miner.yaml
