---
- name: Ensure dependencies
  package:
    name:
    - unzip

- name: Ensure temporary directory exists
  file:
    path: /tmp/hpool-miner
    state: directory

- name: Fetch hpool miner binary
  unarchive:
    src: "https://github.com/hpool-dev/chia-miner/releases/download/{{ hpool_miner_version }}/HPool-Miner-chia-{{ hpool_miner_version }}-linux.zip"
    dest: /tmp/hpool-miner
    remote_src: yes

- name: Ensure bin directory exists
  file:
    path: "{{ bin_dir_path }}"
    state: directory

- name: Copy hpool miner binary to user bin
  copy:
    src: /tmp/hpool-miner/linux/hpool-miner-chia
    dest: "{{ bin_dir_path }}/hpool-miner"
    mode: a+x

- name: Ensure lib directory exists
  file:
    path: "{{ lib_dir_path }}/hpool"
    state: directory

- name: Create hpool config
  template:
    src: templates/hpool-miner-config.yaml.j2
    dest: "{{ lib_dir_path }}/hpool/miner-config.yaml"

- name: Create miner service
  become: yes
  template:
    src: templates/hpool-miner.service.j2
    dest: /etc/systemd/system/hpool-miner.service

- name: Configure miner service
  become: yes
  systemd:
    name: hpool-miner
    enabled: yes
    state: started
