---
- name: Gathering service facts
  service_facts:

- name: Getting Chia node service status
  set_fact:
    chia_node_service: "{{ ansible_facts.services['chia-node.service'] | default({ 'state': 'absent' }) }}"

- name: Defining if the Chia node is running
  set_fact:
    chia_node_is_running: "{{ chia_node_service.state == 'running' }}"

- name: Setup Chia Blockchain
  import_tasks: chia-blockchain.yaml
  when: not chia_node_is_running

- name: Setup Farmr
  import_tasks: farmr.yaml
