---
- name: Checking manager installation
  stat:
    path: "{{ chia_plot_manager_install_path }}"
  register: chia_plot_manager_installation

- name: Checking manager venv creation
  stat:
    path: "{{ chia_plot_manager_install_path }}/venv"
  register: chia_plot_manager_venv


- name: Defining facts regarding plotter installation
  set_fact:
    plotter_is_installed: "{{ chia_plot_manager_installation.stat.exists }}"
    plotter_venv_is_created: "{{ chia_plot_manager_venv.stat.exists }}"

- name: Ensure local src directory
  file:
    path: "{{ install_src_path }}"
    state: directory
  when: not plotter_is_installed

- name: Fetch Swar plot manager source code
  git:
    repo: https://github.com/swar/Swar-Chia-Plot-Manager.git
    dest: "{{ chia_plot_manager_install_path }}"
  when: not plotter_is_installed

- name: Setting dependency names for Ubuntu distributions
  set_fact:
    pip_package_name: python3-pip
  when: ansible_distribution == 'Ubuntu' and not plotter_venv_is_created

- name: Setting dependency names for Arch distributions
  set_fact:
    pip_package_name: python-pip
  when: ansible_distribution == 'Archlinux' and not plotter_venv_is_created

- name: Install dependencies
  become: yes
  package:
    name:
    - "{{ pip_package_name }}"
    - jq
    state: present
  when: not plotter_venv_is_created

- name: Install pip dependencies
  pip:
    name:
    - virtualenv
    - yq
  when: not plotter_venv_is_created

- name: Install requirements
  pip:
    chdir: "{{ chia_plot_manager_install_path }}"
    requirements: requirements.txt
    virtualenv: venv
    virtualenv_command: /usr/bin/python3 -m venv
  when: not plotter_venv_is_created

- name: Copy plotter config
  copy:
    src: "plotter-config-{{ machine_id }}.yaml"
    dest: "{{ chia_plot_manager_install_path }}/config.yaml"

- name: Adds clear plotter binary
  template:
    src: templates/plotter-clear.x.j2
    dest: "{{ bin_dir_path }}/plotter-clear"
    mode: a+x

- name: Adds start plotter binary
  template:
    src: templates/plotter-start.x.j2
    dest: "{{ bin_dir_path }}/plotter-start"
    mode: a+x

- name: Adds stop plotter binary
  template:
    src: templates/plotter-stop.x.j2
    dest: "{{ bin_dir_path }}/plotter-stop"
    mode: a+x

- name: Adds view plotter binary
  template:
    src: templates/plotter-view.x.j2
    dest: "{{ bin_dir_path }}/plotter-view"
    mode: a+x

- name: Adds plotter status binary
  template:
    src: templates/plotter-status.x.j2
    dest: "{{ bin_dir_path }}/plotter-status"
    mode: a+x

- name: Adds restart plotter binary
  template:
    src: templates/plotter-restart.x.j2
    dest: "{{ bin_dir_path }}/plotter-restart"
    mode: a+x

- name: Create plotter service
  become: yes
  template:
    src: templates/chia-plotter.service.j2
    dest: /etc/systemd/system/chia-plotter.service

- name: Configure plotter service
  become: yes
  systemd:
    name: chia-plotter
    enabled: yes
    state: started
