---
- name: Ensure all host storages are properly mounted
  become: yes
  mount:
    path: "{{ mount_dir_path }}/{{ item.mount_dir_name }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  with_items: "{{ attached_storages }}"

- name: Ensure all mounted storages are owner by host user
  become: yes
  file:
    path: "{{ mount_dir_path }}/{{ item.mount_dir_name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items: "{{ attached_storages }}"
