---
- name: Ensure all host harvesters are properly mounted
  become: yes
  mount:
    path: "{{ mount_dir_path }}/harvester-{{ attached_harvester_uuid_hashmap[item] }}"
    src: "UUID={{ item }}"
    fstype: ext4
    state: mounted
  with_items: "{{ attached_harvester_uuids }}"

- name: Ensure all mounted harvesters are owner by host user
  become: yes
  file:
    path: "{{ mount_dir_path }}/harvester-{{ attached_harvester_uuid_hashmap[item] }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items: "{{ attached_harvester_uuids }}"
