---
- name: Getting farmr installation status
  stat:
    path: "{{ farmr_install_path }}"
  register: farmr_installation

- name: Defining if the farmr is installed
  set_fact:
    farmr_is_installed: "{{ farmr_installation.stat.exists == true }}"

- name: Configure blockchain file
  copy:
    src: files/farmr-xfx.json
    dest: "{{ farmr_install_path }}/blockchain/xfx.json"
  when: farmr_is_installed

- name: Update farmr xch config
  template:
    src: templates/farmr-config.json.j2
    dest: "{{ farmr_install_path }}/config/config-xfx.json"

- name: Restart previous farmr service
  become: yes
  systemd:
    name: farmr
    state: restarted
  when: farmr_is_installed
